Name: Ganesh
Location: Daund
DOB: 24/01/2000
Education: BE
Skills: [Linux, Git, GithubActions, DevOps, Docker]

Hobbies:
  -Reading
  -Learning
  -dreaming 
Experiance:
  Devops:
   -Linux:2
   -Docker:2
   -Python:1
   -Azure:4
