---
Name: Ganesh Jagdale
Role: Cloud & DevOps Engineer
Email ID: +91-8806653217
Mo. Number: ganeshjagdale241@gmail.com
Address: At- Daund, Tal. - Daund Dist. - Pune Pin-413801
Linkdin link: linkedin.com/in/ganesh-jagdale
GitHub link: github.com/ganeshjagdale241-crypto.
"": -----------------------------------------------------------------------------------------------------
Summary:
  - -----------------------------------------------------------------------------------------------------
  - Cloud & DevOps Engineer with 4+ years of experience in designing, deploying,
    and managing scalable cloud infrastructure on Microsoft Azure. Experienced
    in Azure IaaS and PaaS services, CI/CD pipeline implementation, automation
    scripting, and infrastructure provisioning. Skilled in Azure DevOps,
    Terraform, Docker, GitHub Actions, Linux administration, and cloud security.
    Proven ability to automate operational tasks, optimize cloud performance,
    and support enterprise production environments.
