---
Name: Ganesh Jagdale
Role: Cloud & DevOps Engineer
Email ID: +91-8806653217
Mo. Number: ganeshjagdale241@gmail.com
Address: At- Daund, Tal. - Daund Dist. - Pune Pin-413801
Linkdin link: linkedin.com/in/ganesh-jagdale
GitHub link: github.com/ganeshjagdale241-crypto.
==============================================================================================:
  =============================================================================================
Summary:
  - Cloud & DevOps Engineer with 4+ years of experience in designing, deploying,
    and managing scalable cloud infrastructure on Microsoft Azure. Experienced
    in Azure IaaS and PaaS services, CI/CD pipeline implementation, automation
    scripting, and infrastructure provisioning. Skilled in Azure DevOps,
    Terraform, Docker, GitHub Actions, Linux administration, and cloud security.
    Proven ability to automate operational tasks, optimize cloud performance,
    and support enterprise production environments.
----------------------------------------------------------------------------------------------------:
  -----------------------------------------------------------------------------------------------------
Key Skills:
  - Cloud Platforms: -Microsoft Azure, AWS (Basics)
  - DevOps & Automation: -Azure DevOps, Terraform, CI/CD Pipelines, GitHub Actions, Jenkins.
  - Containers & Infrastructure: -Docker, Infrastructure as Code (IaC).
  - Programming & Scripting: -Python, PowerShell, Shell Scripting, YAML.
  - Monitoring & Tools: -Grafana, Azure Monitor, ServiceNow, Jira.
  - Operating Systems: -Linux, Windows.
  - Soft Skills: –Teamwork, Incident Response, Troubleshooting, Documentation.
--------------------------------------------------------------------------------------------------:
  ----------------------------------------------------------------------------------------------------
Professional Experience:
  - Azure Cloud Engineer | Tata Consultancy Services	Pune, Hinjewadi-411057|
    07/2022 – Present
  - Managed Azure cloud infrastructure including Virtual Machines, Azure
    Storage, Azure Databricks, Azure Data Factory, Key Vault, and networking
    services.
  - Implemented cloud security best practices using Microsoft Defender for
    Cloud, ensuring compliance and protection against security threats.
  - Configured and maintained access control policies using Azure Active
    Directory, RBAC, and Managed Identities.
  - Monitored cloud infrastructure using Azure Monitor and performance metrics,
    optimizing resource utilization and improving system reliability.
  - Applied backup and disaster recovery strategies to ensure data protection
    and business continuity.
  - Designed and Azure resource tagging strategy using CI/CD pipelines in Azure
    DevOps to improve cost visibility.
  - Automated administrative and operational tasks using PowerShell, Python, and
    Shell scripting, improving        operational efficiency.
  - Executed CI/CD pipelines through GitHub Actions to automate infrastructure
    provisioning and deployment   processes.
  - Collaborated with development and operations teams to troubleshoot cloud
    issues and deliver scalable solutions.
  - Created and updated standard operating procedures (SOPs), runbooks, and
    troubleshooting guides for cloud infrastructure and services.
-----------------------------------------------------------------------------------------------------:
  --------------------------------------------------------------------------------------------------
Key Achievements:
  - Automated RBAC access provisioning using PowerShell scripts, reducing manual
    access provisioning time by 85%.
  - Collaborated with DevOps and L2 teams to improve deployment reliability,
    reducing deployment failures by 70%.
  - Enforced Azure budget alerts and cost monitoring, reducing unexpected cloud
    costs by 20–30%.
  - Recognized by the client for quick learning ability and independently
    handling Azure resource creation tasks.
-----------------------=------------------------------------------------------------------------------:
  ----------------------------------------------------------------------------------------------------
Certifications:
  - Microsoft Azure Administrator Associate (AZ-104)
  - Microsoft Azure Fundamentals (AZ-900)
  - Microsoft Power Platform Developer Associate (PL-400)
  - Google Cloud Associate Certification
  - GitHub Foundations Certification
  - GitHub Actions Certification
---------------------------------------------------------------------------------------------------:
  ---------------------------------------------------------------------------------------------------
Education: ""
Degree: – Bachelor of Engineering
Year: – 2018 - 2022
CGPA: – 8.43/10
